import { useState, useEffect } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home(props) {  

  const [blogs, setBlogs] = useState(props.allBlogs)

  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder - A blog by coder for coders!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <Link href="/">Hunting Coder!</Link>
        </h1>

        <p className={styles.description}>
          Hunting Coder Blog for coders by a <code className={styles.code}>Coder!</code>
        </p>

        <h1>Popular Blogposts</h1>
        <div className={styles.grid}>
        {blogs.slice(0, 4).map((blog, key)=>{
          return (
            <a key={key} href={`/blog/${blog.slug}`} className={styles.card}>
            <Link href={`/blog/${blog.slug}`}><h2>{blog.title} &rarr;</h2></Link>
            <Link href={`/blog/${blog.slug}`}><p>{blog.description}</p></Link>
          </a>
          )
        })}
        <button style={{"marginBottom":"5vh", padding: "3vh", fontSize: "1rem", cursor: "pointer"}}><Link href={"/blog"}>Load More Blogposts</Link></button>
        </div>
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  let data = await fetch("http://localhost:3000/api/blogs/")
  let allBlogs = await data.json()

  return { props: { allBlogs } }
}
